live:
  vaults:
    - ~/notes
  roots:
    - ~/Dropbox
    - ~/Library/CloudStorage/Dropbox
    - ~/cloud/Dropbox
    - ~/cloud/gdrive
    - ~/local
    - ~/Downloads
    - ~/Documents
    - ~/Desktop
    - ~/notes
