#
# Generated by generate_plugin.py.
#
# init.tmux: called by plugin.sh.tmux to initialize the plugin.
#

display -p '[tmux-which-key] Loading plugin ...'

#
# User options
#

set -g @wk_cfg_key_prefix_table "?"
set -g @wk_cfg_title_style "align=centre,bold"
set -g @wk_cfg_title_prefix "tmux actions · Esc closes"
set -g @wk_cfg_title_prefix_style "fg=#89dceb,align=centre,bold"
set -g @wk_cfg_pos_x "C"
set -g @wk_cfg_pos_y "C"

#
# Custom variables
#



#
# Menus
#

set -g @wk_menu_sessions \
'"Work (Option+w)" "w" "switch-client -t =work" \
"Remotes (Option+r)" "r" "switch-client -t =remotes" \
"Last session (Option+Tab)" "Tab" "switch-client -l" \
"Choose session (Option+s)" "s" "choose-tree -sZ" \
"Next session" "n" "switch-client -n" \
"Previous session" "p" "switch-client -p" \
"" \
"New named session" "N" "command-prompt -p \"New session:\" { new-session -s \"%%\" }" \
"Rename session" "R" "command-prompt -I \"#S\" -p \"Rename session:\" { rename-session \"%%\" }" \
"Detach (leave running)" "d" detach-client'

set -g @wk_menu_windows \
'"Choose window (leader+w)" "w" "choose-tree -wZ" \
"Next window" "n" next-window \
"Previous window" "p" previous-window \
"Last window" "Tab" last-window \
"Jump to window number" "g" "command-prompt -p \"Window number:\" { select-window -t \":%%\" }" \
"" \
"New window" "c" "new-window -c \"#{pane_current_path}\"" \
"Rename window" "R" "command-prompt -I \"#W\" -p \"Rename window:\" { rename-window \"%%\" }"'

set -g @wk_menu_panes \
'"Left (Ctrl+h)" "h" "select-pane -L" \
"Down (Ctrl+j)" "j" "select-pane -D" \
"Up (Ctrl+k)" "k" "select-pane -U" \
"Right (Ctrl+l)" "l" "select-pane -R" \
"Show pane numbers" "q" display-panes \
"Zoom / unzoom (leader+z)" "z" "resize-pane -Z" \
"" \
"Split side by side" "v" "split-window -h -c \"#{pane_current_path}\"" \
"Split top / bottom" "s" "split-window -v -c \"#{pane_current_path}\"" \
"Rename pane label" "R" "command-prompt -I \"#T\" -p \"Pane label:\" { select-pane -T \"%%\" }"'

set -g @wk_menu_resizepane \
'"Left (repeat h)" "h" "resize-pane -L 5 ; show-wk-menu #{@wk_menu_resizepane}" \
"Down (repeat j)" "j" "resize-pane -D 5 ; show-wk-menu #{@wk_menu_resizepane}" \
"Up (repeat k)" "k" "resize-pane -U 5 ; show-wk-menu #{@wk_menu_resizepane}" \
"Right (repeat l)" "l" "resize-pane -R 5 ; show-wk-menu #{@wk_menu_resizepane}" \
"Even rows" "e" "select-layout even-vertical"'

set -g @wk_menu_copyandpaste \
'"Copy mode (then v selects, y copies)" "c" copy-mode \
"Choose saved clipboard buffer" "b" "choose-buffer -Z" \
"Paste tmux buffer" "p" "paste-buffer -p"'

set -g @wk_menu_root \
'"+Sessions" "s" "show-wk-menu #{@wk_menu_sessions}" \
"+Windows" "w" "show-wk-menu #{@wk_menu_windows}" \
"+Panes" "p" "show-wk-menu #{@wk_menu_panes}" \
"+Resize pane" "r" "show-wk-menu #{@wk_menu_resizepane}" \
"+Copy and paste" "c" "show-wk-menu #{@wk_menu_copyandpaste}" \
"" \
"Full shortcut cheat sheet" "?" "display-popup -E -w 88% -h 85% -T \" tmux shortcuts · q closes \" \"less -R ~/.config/tmux/shortcuts.txt\"" \
"All live key bindings" "B" list-keys'

#
# Macros
#

set -gF @wk_cmd_show \
"display-menu \
-x '#{@wk_cfg_pos_x}' \
-y '#{@wk_cfg_pos_y}' \
-T '#[#{@wk_cfg_title_style}]#[#{@wk_cfg_title_prefix_style}]#{@wk_cfg_title_prefix}#[#{@wk_cfg_title_style}]'"

set -gF command-alias[200] show-wk-menu=\
'#{@wk_cmd_show}'

set -gF command-alias[201] show-wk-menu-root=\
'#{@wk_cmd_show} #{@wk_menu_root}'

#
# Keybindings
#

display -p "[tmux-which-key] Binding prefix table key to #{@wk_cfg_key_prefix_table} ..."
run-shell "tmux bind-key -Tprefix #{@wk_cfg_key_prefix_table} show-wk-menu-root"

display -p '[tmux-which-key] Done'
