name: dev
root: ~/local/code/python/prototyped-pair-finder

windows:
  - main:
      layout: even-vertical
      panes:
        - claude-code:
          - tmux select-pane -T "claude-code"
          - claude --permission-mode bypassPermissions
        - terminal:
          - tmux select-pane -T "terminal"
        - pymol:
          - tmux select-pane -T "pymol"
