name: dev
root: ~/local/code/python/prototyped-pair-finder

windows:
  - main:
      layout: even-vertical
      panes:
        - claude-code: claude --permission-mode bypassPermissions
        - pymol:
        - terminal:
